language: android
jdk: openjdk17

android:
  components:
    - tools
    - platform-tools
    - build-tools-34.0.0
    - android-32
    - android-24
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository


before_install:
  - chmod +x gradlew
  #- yes | ~/Android/Sdk/tools/bin/sdkmanager --licenses
  - yes | sdkmanager "platforms;android-33

#before_install:
#  - yes | sdkmanager "platforms;android-32"

#script:
#  - ./gradlew clean build


install:
  # Download and install the latest version of Android SDK Command Line Tools
  - wget -q "https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip" -O android-sdk-tools.zip
  - unzip -q android-sdk-tools.zip -d $HOME/android-sdk
  - export ANDROID_SDK_ROOT=$HOME/android-sdk
  - export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/bin
  - echo "y" | sdkmanager --sdk_root=$ANDROID_SDK_ROOT --update
